#!/bin/bash

nginx_server=root@192.168.1.126
remote_nginx_root=/usr/local/nginx
remote_nginx_bin=${remote_nginx_root}/sbin/nginx
nginx_server_max_cores=8

bench_server=root@192.168.1.66
remote_project_root=/root/workspace/bench-nginx-ssl-qat
bench_server_openssl_max_s_time=1600
bench_server_openssl_repeats=1

# \begin configurations
dim_ids=()
dim_ids[${#dim_ids[@]}]="qat_async"

declare -A nginx_conf
nginx_conf+=( ["qat_async"]="nginx_qat_async.conf" )
# \end configurations
